#!/usr/bin/env python3
"""
Orchestration engine for generating command schemas from a database.
This script is generated by Antigravity.
"""

import os
import sys
import json
import time
import urllib.request
import urllib.error
from pathlib import Path
import re

# 1. Retrieve Environment Variables
TMP_AGENT_PORT = os.environ.get("TMP_AGENT_PORT", "0")
TMP_DB_PATH = os.environ.get("TMP_DB_PATH", "")
TMP_CONFIG_DIR = os.environ.get("TMP_CONFIG_DIR", "")

if not TMP_CONFIG_DIR:
    TMP_CONFIG_DIR = str(Path.home() / ".config" / "tmp")

BASE_URL = f"http://127.0.0.1:{TMP_AGENT_PORT}"

def log_progress(message: str, level: str = "info"):
    """Log progress to the loopback server's /log endpoint and sys.stdout/sys.stderr."""
    print(f"[{level.upper()}] {message}", file=sys.stderr if level == "error" else sys.stdout)
    url = f"{BASE_URL}/log"
    payload = {"level": level, "message": message}
    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=5) as response:
            pass
    except Exception:
        # Non-blocking error if localhost log endpoint is not up
        pass

def make_request(url: str, method: str = "GET", payload: dict = None) -> dict:
    """Helper function to execute HTTP requests using urllib.request."""
    req_data = None
    headers = {}
    if payload is not None:
        req_data = json.dumps(payload).encode("utf-8")
        headers = {"Content-Type": "application/json"}
    
    req = urllib.request.Request(url, data=req_data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=15) as res:
            resp_body = res.read().decode("utf-8")
            if not resp_body:
                return {}
            return json.loads(resp_body)
    except urllib.error.HTTPError as e:
        error_msg = e.read().decode("utf-8") if e.fp else str(e)
        raise RuntimeError(f"HTTP Error {e.code} for {method} {url}: {error_msg}")
    except Exception as e:
        raise RuntimeError(f"Request failed for {method} {url}: {e}")

def extract_json_array(text: str) -> list:
    """Extract a list or JSON array robustly from a string output which might contain markdown formatting."""
    text = text.strip()
    # Try direct parse
    try:
        data = json.loads(text)
        if isinstance(data, list):
            return data
    except Exception:
        pass

    # Try searching for ```json [...] ```
    code_block_match = re.search(r'```json\s*([\s\S]*?)\s*```', text, re.IGNORECASE)
    if code_block_match:
        try:
            data = json.loads(code_block_match.group(1).strip())
            if isinstance(data, list):
                return data
        except Exception:
            pass

    # Try generic code block ``` [...] ```
    code_block_match = re.search(r'```\s*([\s\S]*?)\s*```', text)
    if code_block_match:
        try:
            data = json.loads(code_block_match.group(1).strip())
            if isinstance(data, list):
                return data
        except Exception:
            pass

    # Find first '[' and matching last ']'
    start_idx = text.find('[')
    end_idx = text.rfind(']')
    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        candidate = text[start_idx:end_idx+1]
        try:
            data = json.loads(candidate)
            if isinstance(data, list):
                return data
        except Exception:
            pass

    # Try finding an object instead of array and wrap it in a list
    start_idx_obj = text.find('{')
    end_idx_obj = text.rfind('}')
    if start_idx_obj != -1 and end_idx_obj != -1 and end_idx_obj > start_idx_obj:
        candidate_obj = text[start_idx_obj:end_idx_obj+1]
        try:
            data = json.loads(candidate_obj)
            if isinstance(data, dict):
                return [data]
        except Exception:
            pass

    raise ValueError("Could not extract a valid JSON array or object from output contents.")

def main():
    log_progress("Starting workflow.py orchestration engine.")
    
    # Validation
    if not TMP_DB_PATH:
        log_progress("Validation failed: TMP_DB_PATH environment variable is empty or not set.", level="error")
        sys.exit(1)
    
    db_path = Path(TMP_DB_PATH)
    tool_name = db_path.stem if db_path.name else "db_tool"
    log_progress(f"Calculated tool_name as '{tool_name}' from TMP_DB_PATH='{TMP_DB_PATH}'.")
    log_progress(f"TMP_CONFIG_DIR set to: {TMP_CONFIG_DIR}")
    log_progress(f"TMP_AGENT_PORT set to: {TMP_AGENT_PORT}")
    
    # 5. Query /db/tables to get the list of tables
    log_progress("Querying database tables from the /db/tables endpoint.")
    try:
        tables_resp = make_request(
            f"{BASE_URL}/db/tables", 
            "POST", 
            {"connection": {"sqlite_path": str(db_path.absolute())}}
        )
    except Exception as e:
        log_progress(f"Failed to query database tables: {e}", level="error")
        sys.exit(1)
        
    tables = []
    if isinstance(tables_resp, list):
        tables = tables_resp
    elif isinstance(tables_resp, dict):
        tables = tables_resp.get("tables") or tables_resp.get("table_names") or tables_resp.get("data") or []
    
    if not tables:
        log_progress("No tables found in the database or tables response format was invalid.", level="error")
        sys.exit(1)
        
    log_progress(f"Found {len(tables)} table(s): {', '.join(tables)}")
    
    active_subagents = {} # subagent_id: table_name
    failed = False
    
    # 6. For each table, query columns and spawn subagent
    for table_name in tables:
        log_progress(f"Fetching columns for table '{table_name}'.")
        try:
            col_resp = make_request(
                f"{BASE_URL}/db/columns",
                "POST",
                {
                    "table_name": table_name,
                    "connection": {"sqlite_path": str(db_path.absolute())}
                }
            )
        except Exception as e:
            log_progress(f"Failed to fetch columns for table '{table_name}': {e}", level="error")
            failed = True
            continue
            
        columns = []
        if isinstance(col_resp, list):
            columns = col_resp
        elif isinstance(col_resp, dict):
            columns = col_resp.get("columns") or col_resp.get("fields") or col_resp.get("data") or []
            
        log_progress(f"Table '{table_name}' has columns: {json.dumps(columns)}")
        
        # 7. Generate a prompt for a subagent for each table
        prompt = (
            f"You are a database tool CLI command schema generator. "
            f"Analyze the database table '{table_name}' with the following columns: {json.dumps(columns)}.\n"
            f"Generate concrete CLI command schema objects representing four operations: 'select', 'insert', 'delete', and 'query'.\n"
            f"Each command schema object must strictly match this exact JSON structure (all fields required):\n"
            f'{{"command": "string", "description": "string", "group": "string", "verified": false, "tokens": []}}\n\n'
            f"Rules for fields:\n"
            f"- 'command': The CLI command string (e.g. 'select-{table_name}')\n"
            f"- 'description': Human-friendly text of what it does\n"
            f"- 'group': Always '{table_name}'\n"
            f"- 'verified': false\n"
            f"- 'tokens': []\n\n"
            f"Format your response as a valid, parsable JSON array containing exactly these 4 command objects. "
            f"Do not write conversational preamble. Return ONLY the JSON content."
        )
        
        # 8. Spawn background subagent
        log_progress(f"Spawning background subagent for table '{table_name}'.")
        try:
            spawn_resp = make_request(f"{BASE_URL}/subagent", "POST", {"prompt": prompt})
            subagent_id = spawn_resp.get("subagent_id") or spawn_resp.get("id")
            if not subagent_id:
                raise ValueError("Response missing both 'subagent_id' and 'id' fields.")
            
            active_subagents[subagent_id] = table_name
            log_progress(f"Successfully spawned subagent '{subagent_id}' for table '{table_name}'.")
        except Exception as e:
            log_progress(f"Failed to spawn subagent for table '{table_name}': {e}", level="error")
            failed = True
            
    if not active_subagents:
        log_progress("No subagents successfully spawned. Exiting.", level="error")
        sys.exit(1)
        
    # 9. Periodically poll /subagent/<subagent_id>
    log_progress(f"Entering polling loop for {len(active_subagents)} active subagent(s).")
    results = {}
    pending_ids = list(active_subagents.keys())
    
    while pending_ids:
        time.sleep(1)
        still_pending = []
        for s_id in pending_ids:
            t_name = active_subagents[s_id]
            try:
                poll_resp = make_request(f"{BASE_URL}/subagent/{s_id}", "GET")
                status = poll_resp.get("status")
                
                if status in ["Success", "Failure"]:
                    results[t_name] = {
                        "status": status,
                        "output": poll_resp.get("output", "")
                    }
                    log_progress(f"Subagent {s_id} for table '{t_name}' completed with status: {status}")
                else:
                    still_pending.append(s_id)
            except Exception as e:
                results[t_name] = {
                    "status": "Failure",
                    "output": f"Error during polling: {e}"
                }
                log_progress(f"Polling error for subagent {s_id} (table '{t_name}'): {e}", level="error")
                
        pending_ids = still_pending
        
    # 11. Aggregate the generated command schema arrays from all successful subagents
    log_progress("Aggregating output from subagents.")
    aggregated_commands = []
    
    for t_name, res in results.items():
        if res["status"] != "Success":
            log_progress(f"Subagent for table '{t_name}' failed or errored: {res['status']}", level="error")
            failed = True
            continue
            
        try:
            chunks = extract_json_array(res["output"])
            parsed_chunks = []
            for chunk in chunks:
                if isinstance(chunk, dict):
                    parsed_chunks.append({
                        "command": str(chunk.get("command", "")),
                        "description": str(chunk.get("description", "")),
                        "group": str(chunk.get("group", t_name)),
                        "verified": bool(chunk.get("verified", False)),
                        "tokens": list(chunk.get("tokens", []))
                    })
            aggregated_commands.extend(parsed_chunks)
            log_progress(f"Successfully aggregated {len(parsed_chunks)} commands from table '{t_name}'.")
        except Exception as e:
            log_progress(f"Failed to extract JSON array for table '{t_name}': {e}", level="error")
            failed = True
            
    # 12. Combine schema JSON
    final_schema = {
        "meta": {
            "tool": tool_name,
            "version": 1,
            "verified": True,
            "keywords": ["database", tool_name]
        },
        "commands": aggregated_commands
    }
    
    # 13. Save this schema file
    config_path = Path(TMP_CONFIG_DIR)
    schema_dir = config_path / "schemas"
    schema_file = schema_dir / f"{tool_name}.json"
    
    try:
        schema_dir.mkdir(parents=True, exist_ok=True)
        with open(schema_file, "w", encoding="utf-8") as sf:
            json.dump(final_schema, sf, indent=2)
        log_progress(f"Successfully wrote schema to {schema_file.absolute()}")
    except Exception as e:
        log_progress(f"Failed to save schema file: {e}", level="error")
        failed = True
        
    if failed:
        log_progress("Workflow completed with failures/errors.", level="error")
        sys.exit(1)
    else:
        log_progress("Workflow completed successfully!")
        sys.exit(0)

if __name__ == "__main__":
    main()
