use std::path::PathBuf;
use tmp_core::config::default_config_path;
use tmp_core::schema::Schema;

/// Generates a draft RTK-compatible TOML filter for a TMP operation.
pub fn run(
    operation_id: &str,
    config_path: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    // 1. Find schemas and locate the matching operation
    let config_file_path = match config_path {
        Some(p) => PathBuf::from(p),
        None => default_config_path().ok_or("Could not determine config directory")?,
    };
    let schemas_dir = config_file_path
        .parent()
        .ok_or("Invalid config path")?
        .join("schemas");

    // Parse operation_id like "cargo.test" -> tool="cargo", command contains "test"
    let parts: Vec<&str> = operation_id.splitn(2, '.').collect();
    if parts.len() != 2 {
        return Err(format!(
            "Invalid operation-id format '{}'. Expected 'tool.command' (e.g. 'cargo.test')",
            operation_id
        )
        .into());
    }
    let (tool_name, op_suffix) = (parts[0], parts[1]);

    // 2. Load the tool's schema
    let schema_path = schemas_dir.join(format!("{}.json", tool_name));
    if !schema_path.exists() {
        return Err(format!("Schema for tool '{}' not found", tool_name).into());
    }
    let content = std::fs::read_to_string(&schema_path)?;
    let schema = Schema::from_json(&content).map_err(|e| format!("Invalid schema: {}", e))?;

    // 3. Find the matching operation
    let op = schema
        .operations
        .iter()
        .find(|o| o.command.contains(op_suffix))
        .ok_or(format!(
            "Operation '{}' not found in schema '{}'",
            op_suffix, tool_name
        ))?;

    // 4. Generate draft RTK filter TOML
    let filter_name = operation_id.replace('.', "-");
    let first_word = op.command.split_whitespace().next().unwrap_or(&op.command);
    let command_pattern = format!("^{}\\b", regex_escape(first_word));

    let toml = format!(
        r#"# Draft RTK filter generated by TMP
# Status: UNVERIFIED — review and test before trusting
# Operation: {operation_id}
# Command: {command}

[filters."{filter_name}"]
description = "Compact {description} output"
match_command = "{command_pattern}"
strip_ansi = true
strip_lines_matching = [
    "^\\s*$",
    "^\\s+Compiling",
    "^\\s+Downloading",
    "^\\s+Finished",
]
max_lines = 80
on_empty = "{operation_id}: ok"

[[tests."{filter_name}"]]
name = "preserves key output"
input = "<paste representative command output here>"
expected = "<paste expected filtered output here>"
"#,
        operation_id = operation_id,
        command = op.command,
        filter_name = filter_name,
        description = op.description,
        command_pattern = command_pattern,
    );

    // 5. Write to .rtk/filters.toml or print
    let cwd = std::env::current_dir()?;
    let rtk_dir = cwd.join(".rtk");
    std::fs::create_dir_all(&rtk_dir)?;
    let filter_path = rtk_dir.join("filters.toml");

    if filter_path.exists() {
        // Append
        let existing = std::fs::read_to_string(&filter_path)?;
        std::fs::write(&filter_path, format!("{}\n{}", existing, toml))?;
    } else {
        std::fs::write(&filter_path, &toml)?;
    }

    println!("Draft RTK filter written to {}", filter_path.display());
    println!("⚠ This filter is UNVERIFIED. Review and test before use.");

    Ok(())
}

fn regex_escape(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '.' | '*' | '+' | '?' | '(' | ')' | '[' | ']' | '{' | '}' | '\\' | '^' | '$' | '|' => {
                format!("\\{}", c)
            }
            _ => c.to_string(),
        })
        .collect()
}
